// <auto-generated />
using System;
using EmployeeManagement.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Repository.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Aggregator.Entities.DepartmentAggregatorRoot", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Finance"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Aggregator.Entities.EmployeeAggregatorRoot", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportingManagerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReportingManagerId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "rahim@gmail.com",
                            EmploymentType = "Full-Time",
                            Gender = "Male",
                            JobTitle = "Software Engineer",
                            JoiningDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rahim Ahmed",
                            Phone = "01711111111",
                            Salary = 45000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "karim@gmail.com",
                            EmploymentType = "Full-Time",
                            Gender = "Male",
                            JobTitle = "HR Executive",
                            JoiningDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karim Hasan",
                            Phone = "01722222222",
                            Salary = 35000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "nusrat@gmail.com",
                            EmploymentType = "Full-Time",
                            Gender = "Female",
                            JobTitle = "Accountant",
                            JoiningDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nusrat Jahan",
                            Phone = "01733333333",
                            Salary = 40000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "hasan@gmail.com",
                            EmploymentType = "Contract",
                            Gender = "Male",
                            JobTitle = "Web Developer",
                            JoiningDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hasan Mahmud",
                            Phone = "01744444444",
                            Salary = 50000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6
                        },
                        new
                        {
                            EmployeeId = 5,
                            CreatedAt = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "sadia@gmail.com",
                            EmploymentType = "Full-Time",
                            Gender = "Female",
                            JobTitle = "HR Manager",
                            JoiningDate = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sadia Akter",
                            Phone = "01755555555",
                            Salary = 60000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Aggregator.Entities.EmployeeAggregatorRoot", b =>
                {
                    b.HasOne("EmployeeManagement.Aggregator.Entities.DepartmentAggregatorRoot", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeManagement.Aggregator.Entities.EmployeeAggregatorRoot", "ReportingManager")
                        .WithMany()
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("ReportingManager");
                });
#pragma warning restore 612, 618
        }
    }
}
