<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LeaveManagement.DTO\LeaveManagement.DTO.csproj" />
    <ProjectReference Include="..\LeaveManagement.Aggregator\LeaveManagement.Aggregator.csproj" />
    <ProjectReference Include="..\LeaveManagement.Repository\LeaveManagement.Repository.csproj" />
    <ProjectReference Include="..\..\HRPlatform.Shared\HRPlatform.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
