<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeaveManagement.DTO\LeaveManagement.DTO.csproj" />
    <ProjectReference Include="..\LeaveManagement.Handler\LeaveManagement.Handler.csproj" />
    <ProjectReference Include="..\..\HRPlatform.Shared\HRPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
