<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authentication.Aggregator\Authentication.Aggregator.csproj" />
    <ProjectReference Include="..\Authentication.DTO\Authentication.DTO.csproj" />
    <ProjectReference Include="..\Authentication.Repository\Authentication.Repository.csproj" />
    <ProjectReference Include="..\..\HRPlatform.Shared\HRPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
