// <auto-generated />
using System;
using LeaveManagement.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagement.Repository.Migrations
{
    [DbContext(typeof(LeaveDbContext))]
    [Migration("20260902080543_AddLeaveBalanceSeed")]
    partial class AddLeaveBalanceSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagement.Aggregator.Entities.LeaveBalance", b =>
                {
                    b.Property<int>("LeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveBalanceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("HeldDays")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LeaveBalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            LeaveBalanceId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            HeldDays = 0,
                            LeaveTypeId = 1,
                            RowVersion = new byte[0],
                            TotalDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedDays = 0,
                            Year = 2026
                        },
                        new
                        {
                            LeaveBalanceId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            HeldDays = 0,
                            LeaveTypeId = 2,
                            RowVersion = new byte[0],
                            TotalDays = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedDays = 0,
                            Year = 2026
                        },
                        new
                        {
                            LeaveBalanceId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            HeldDays = 0,
                            LeaveTypeId = 3,
                            RowVersion = new byte[0],
                            TotalDays = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedDays = 0,
                            Year = 2026
                        },
                        new
                        {
                            LeaveBalanceId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            HeldDays = 0,
                            LeaveTypeId = 1,
                            RowVersion = new byte[0],
                            TotalDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedDays = 2,
                            Year = 2026
                        },
                        new
                        {
                            LeaveBalanceId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 5,
                            HeldDays = 0,
                            LeaveTypeId = 1,
                            RowVersion = new byte[0],
                            TotalDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsedDays = 0,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagement.Aggregator.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveRequestId"));

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            LeaveRequestId = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            EndDate = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveTypeId = 1,
                            Reason = "Family vacation",
                            RequestedAt = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalDays = 3,
                            UpdatedAt = new DateTime(2026, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveRequestId = 2,
                            ApprovedByEmployeeId = 5,
                            CreatedAt = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            EndDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveTypeId = 1,
                            Reason = "Personal work",
                            RequestedAt = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedAt = new DateTime(2026, 8, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            TotalDays = 2,
                            UpdatedAt = new DateTime(2026, 8, 2, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveRequestId = 3,
                            ApprovedByEmployeeId = 5,
                            CreatedAt = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            EndDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeaveTypeId = 3,
                            Reason = "Urgent travel",
                            RejectionReason = "Critical release scheduled on those dates",
                            RequestedAt = new DateTime(2026, 6, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedAt = new DateTime(2026, 6, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected",
                            TotalDays = 2,
                            UpdatedAt = new DateTime(2026, 6, 26, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeaveManagement.Aggregator.Entities.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultDaysPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            Code = "ANNUAL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDaysPerYear = 20,
                            Description = "Standard annual leave",
                            IsActive = true,
                            Name = "Annual Leave",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            Code = "SICK",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDaysPerYear = 10,
                            Description = "Standard sick leave",
                            IsActive = true,
                            Name = "Sick Leave",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            Code = "CASUAL",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDaysPerYear = 5,
                            Description = "Casual / personal leave",
                            IsActive = true,
                            Name = "Casual Leave",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LeaveManagement.Aggregator.Entities.LeaveBalance", b =>
                {
                    b.HasOne("LeaveManagement.Aggregator.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("LeaveManagement.Aggregator.Entities.LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagement.Aggregator.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });
#pragma warning restore 612, 618
        }
    }
}
